name: Deploy to Amazon EC2

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: ap-southeast-2
  S3_BUCKET_NAME: grabpt-github-actions-s3-bucket
  CODE_DEPLOY_APPLICATION_NAME: grabpt-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: grabpt-codedeploy-deployment-group
  AWS_DEFAULT_REGION: ap-southeast-2
  AWS_S3_ACL: bucket-owner-full-control

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create .env.properties file from secret
        run: echo "${{ secrets.ENV_PROPERTIES }}" > .env

      - name: Build with Gradle (skip tests)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x test

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/
          cp -r scripts appspec.yml .env deploy/

      - name: Zip deployment
        run: |
          zip -r $GITHUB_SHA.zip deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-zip
          path: ${{ github.sha }}.zip

  upload:
    name: Upload to S3
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3 with ACL
        run: |
          aws s3 cp $GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
            --acl bucket-owner-full-control

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: upload

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name $CODE_DEPLOY_APPLICATION_NAME \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name $CODE_DEPLOY_DEPLOYMENT_GROUP_NAME \
            --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip
